export const GET_POKEMONS_REQUEST = 'GET_POKEMONS_REQUEST';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMONS_FAIL = 'GET_POKEMONS_FAIL';

export const GET_POKEMON_REQUEST = 'GET_POKEMON_REQUEST';
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_FAIL = 'GET_POKEMON_FAIL';

export const LOADER_POKEMONS_SUCCESS = "LOADER_POKEMONS_SUCCESS"
